# Generated by Django 3.0.11 on 2020-12-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-is_promoted', '-publish_date')},
        ),
        migrations.AddField(
            model_name='article',
            name='expiration_date',
            field=models.DateTimeField(blank=True, help_text='Valid until date', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='is_promoted',
            field=models.BooleanField(default=False, help_text='should be displayed first, for important articles'),
            preserve_default=False,
        ),
    ]
