# Generated by Django 3.0.11 on 2020-12-23 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_auto_20201223_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='university_private_note',
            field=models.TextField(blank=True, help_text='Informatii private adaugate de universitate pentru acest articol', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='university_public_note',
            field=models.TextField(blank=True, help_text='Informatii publice adaugate de universitate pentru acest articol', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='was this approved by an admin for publishing'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_promoted',
            field=models.BooleanField(default=False, help_text='should be displayed first, for important articles'),
        ),
        migrations.CreateModel(
            name='HistoricalArticle',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.TextField(help_text='the article title')),
                ('content', models.TextField(help_text='the article content')),
                ('created_date', models.DateTimeField(blank=True, editable=False, help_text='Date the article was created')),
                ('publish_date', models.DateTimeField(help_text='Date the article was published')),
                ('expiration_date', models.DateTimeField(blank=True, help_text='Valid until date', null=True)),
                ('is_approved', models.BooleanField(default=False, help_text='was this approved by an admin for publishing')),
                ('is_promoted', models.BooleanField(default=False, help_text='should be displayed first, for important articles')),
                ('university_public_note', models.TextField(blank=True, help_text='Informatii publice adaugate de universitate pentru acest articol', null=True)),
                ('university_private_note', models.TextField(blank=True, help_text='Informatii private adaugate de universitate pentru acest articol', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, help_text='article author', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical article',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
