# Generated by Django 3.0.11 on 2021-02-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210106_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='the tag shortname')),
                ('description', models.TextField(help_text='the tag explanaition')),
                ('color', models.TextField(help_text="the tag's color, may be useful to keep consistency on fe, ex: 'blue")),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='articles.ArticleTag'),
        ),
    ]
