# Generated by Django 3.0.11 on 2020-12-23 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text="company's name")),
                ('description', models.TextField(help_text='description of the company')),
                ('email', models.EmailField(help_text="company's email", max_length=254)),
                ('phone', models.TextField(blank=True, help_text="company's phone", null=True)),
                ('adress', models.TextField(help_text='adresa fizica (de preferat din Cluj) a companiei')),
                ('website', models.URLField(blank=True, help_text='website-ul companiei', null=True)),
                ('facebook', models.URLField(blank=True, help_text='pagina de facebook a companiei', null=True)),
                ('linkdin', models.URLField(blank=True, help_text='pagina de linkdin a companiei', null=True)),
                ('university_public_note', models.TextField(blank=True, help_text='Informatii publice adaugate de universitate pentru aceasta companie', null=True)),
                ('university_private_note', models.TextField(blank=True, help_text='Informatii private adaugate de universitate pentru aceasta companie', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCompany',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.TextField(help_text="company's name")),
                ('description', models.TextField(help_text='description of the company')),
                ('email', models.EmailField(help_text="company's email", max_length=254)),
                ('phone', models.TextField(blank=True, help_text="company's phone", null=True)),
                ('adress', models.TextField(help_text='adresa fizica (de preferat din Cluj) a companiei')),
                ('website', models.URLField(blank=True, help_text='website-ul companiei', null=True)),
                ('facebook', models.URLField(blank=True, help_text='pagina de facebook a companiei', null=True)),
                ('linkdin', models.URLField(blank=True, help_text='pagina de linkdin a companiei', null=True)),
                ('university_public_note', models.TextField(blank=True, help_text='Informatii publice adaugate de universitate pentru aceasta companie', null=True)),
                ('university_private_note', models.TextField(blank=True, help_text='Informatii private adaugate de universitate pentru aceasta companie', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical company',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
