# Generated by Django 3.0.11 on 2021-01-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='has_gold_status',
            field=models.BooleanField(default=False, help_text='company is a valued partener of our university'),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='has_gold_status',
            field=models.BooleanField(default=False, help_text='company is a valued partener of our university'),
        ),
    ]
