# Generated by Django 3.0.11 on 2021-02-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20210106_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='short_description',
            field=models.TextField(default='Short description', help_text='short description of the company, appears in list of companies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='short_description',
            field=models.TextField(default='short description', help_text='short description of the company, appears in list of companies'),
            preserve_default=False,
        ),
    ]
